# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-18 04:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tgt_moni_info',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('tgt_ssh_status', models.IntegerField(default=0, verbose_name='\u76ee\u6807\u7aefssh\u8fde\u901a\u72b6\u6001')),
                ('tgt_path_status', models.IntegerField(default=0, verbose_name='\u76ee\u6807\u7aef\u76ee\u5f55\u72b6\u6001')),
                ('exec_script_status', models.IntegerField(default=0, verbose_name='\u76ee\u6807\u7aef\u8fdc\u7a0b\u811a\u672c\u76ee\u5f55\u72b6\u6001')),
                ('sync_status', models.IntegerField(default=0, verbose_name='\u540c\u6b65\u72b6\u6001')),
                ('active', models.IntegerField(default=0, verbose_name='\u540c\u6b65\u52a8\u4f5c')),
                ('collect_cnt', models.IntegerField(null=True, verbose_name='\u63a5\u6536\u8fdb\u7a0b\u6570')),
                ('collect_err', models.CharField(max_length=200, null=True, verbose_name='\u63a5\u6536\u8fdb\u7a0b\u62a5\u9519\u4fe1\u606f')),
                ('loader_s_cnt', models.IntegerField(null=True, verbose_name='\u5168\u91cf\u52a0\u8f7d\u8fdb\u7a0b\u6570')),
                ('loader_r_cnt', models.IntegerField(null=True, verbose_name='\u589e\u91cf\u52a0\u8f7d\u8fdb\u7a0b\u6570')),
                ('loader_s_p_cnt', models.IntegerField(null=True, verbose_name='\u5168\u91cf\u52a0\u8f7d\u914d\u7f6e\u8fdb\u7a0b\u6570')),
                ('loader_r_p_cnt', models.IntegerField(null=True, verbose_name='\u589e\u91cf\u52a0\u8f7d\u914d\u7f6e\u8fdb\u7a0b\u6570')),
                ('loader_rate', models.CharField(max_length=200, null=True, verbose_name='\u52a0\u8f7d\u8fdb\u5ea6\u4fe1\u606f')),
                ('loader_time', models.CharField(max_length=200, null=True, verbose_name='\u52a0\u8f7d\u65f6\u95f4\u4fe1\u606f')),
                ('loader_err', models.CharField(max_length=200, null=True, verbose_name='\u52a0\u8f7d\u62a5\u9519\u4fe1\u606f')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u76d1\u63a7\u4fe1\u606f\u6dfb\u52a0\u65f6\u95f4')),
                ('queue_id', models.ForeignKey(db_column=b'queue_id', on_delete=django.db.models.deletion.CASCADE, to='ormapp.rep_queue', verbose_name='\u961f\u5217ID\u4fe1\u606f')),
            ],
            options={
                'db_table': 'tgt_moni_info',
                'verbose_name': '\u76ee\u6807\u7aef\u76d1\u63a7\u4fe1\u606f\u8868',
                'verbose_name_plural': '\u76ee\u6807\u7aef\u76d1\u63a7\u4fe1\u606f\u8868',
            },
        ),
    ]
