# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-18 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0002_tgt_moni_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgt_moni_info',
            name='active',
            field=models.IntegerField(null=True, verbose_name='\u540c\u6b65\u52a8\u4f5c'),
        ),
        migrations.AlterField(
            model_name='tgt_moni_info',
            name='sync_status',
            field=models.IntegerField(null=True, verbose_name='\u540c\u6b65\u72b6\u6001'),
        ),
    ]
